/**
 * Console output renderer for PromptShield
 * Provides colored, readable output for CLI screenshots
 */

import { ScanResult, Violation } from '../../types/core/rule';
import { OutputContext } from '../../types/core/outputFormat';
import { OutputRenderer } from './index';
import chalk from 'chalk';

export class ConsoleRenderer implements OutputRenderer {
  render(results: ScanResult[], context: OutputContext): string {
    let output = this.renderHeader(context);
    output += this.renderSummary(context);
    output += this.renderResults(results);
    output += this.renderFooter(context);

    return output;
  }

  private renderHeader(context: OutputContext): string {
    let header = chalk.blue.bold('🔒 PromptShield Scan Report\n');
    header += chalk.blue('================================\n\n');

    header += chalk.white(`📅 Scan Date: ${context.metadata.scanDate}\n`);
    if (context.metadata.rulepack) {
      header += chalk.white(`📦 RulePack: ${context.metadata.rulepack}\n`);
    }
    header += chalk.white(`📁 Files Scanned: ${context.metadata.fileCount}\n`);
    header += chalk.white(
      `🚨 Total Violations: ${context.metadata.totalViolations}\n\n`
    );

    return header;
  }

  private renderSummary(context: OutputContext): string {
    let summary = chalk.cyan.bold('📊 Summary\n');
    summary += chalk.cyan('==========\n\n');

    // Severity breakdown
    summary += chalk.yellow.bold('Severity Breakdown:\n');
    for (const [severity, count] of Object.entries(
      context.metadata.severityBreakdown
    )) {
      const color =
        severity === 'critical'
          ? chalk.red
          : severity === 'high'
            ? chalk.yellow
            : chalk.blue;
      summary += `  ${color(`• ${severity}: ${count} violations`)}\n`;
    }
    summary += '\n';

    // Category breakdown
    summary += chalk.yellow.bold('Category Breakdown:\n');
    for (const [category, count] of Object.entries(
      context.metadata.categoryBreakdown
    )) {
      summary += `  ${chalk.blue(`• ${category}: ${count} violations`)}\n`;
    }
    summary += '\n';

    return summary;
  }

  private renderResults(results: ScanResult[]): string {
    if (results.length === 0) {
      return chalk.green.bold('✅ No files were processed.\n\n');
    }

    let resultsSection = chalk.cyan.bold('📄 Results\n');
    resultsSection += chalk.cyan('==========\n\n');

    for (const result of results) {
      // File header
      resultsSection += chalk.white.bold(`📄 File: ${result.file}\n`);
      resultsSection += chalk.gray('─'.repeat(50)) + '\n\n';

      if (result.violations.length === 0) {
        resultsSection += chalk.green('✅ No violations found.\n\n');
      } else {
        // Group violations by rule ID
        const groupedViolations = this.groupViolationsByRule(result.violations);

        for (const [ruleId, violations] of groupedViolations) {
          const firstViolation = violations[0];
          const severityColor =
            firstViolation.severity === 'critical' ? chalk.red : chalk.yellow;
          const severityIcon =
            firstViolation.severity === 'critical' ? '🚨' : '⚠️';

          resultsSection += `${severityIcon} ${severityColor.bold(`[${firstViolation.severity.toUpperCase()}]`)} ${chalk.white.bold(ruleId)} (${chalk.blue(firstViolation.category)})\n`;
          resultsSection += chalk.gray(`Rule: ${firstViolation.message}\n`);
          resultsSection += chalk.gray(`Occurrences: ${violations.length}\n\n`);

          // List matches
          for (const violation of violations) {
            const context =
              violation.objectIndex !== undefined
                ? ` [Object ${violation.objectIndex}, field: ${violation.field}]`
                : '';
            resultsSection += `  ${chalk.red('•')} ${chalk.white(`"${violation.match}"`)}${chalk.gray(context)}\n`;
          }
          resultsSection += '\n';
        }
      }
    }

    return resultsSection;
  }

  private groupViolationsByRule(
    violations: Violation[]
  ): Map<string, Violation[]> {
    const grouped = new Map<string, Violation[]>();

    for (const violation of violations) {
      if (!grouped.has(violation.ruleId)) {
        grouped.set(violation.ruleId, []);
      }
      grouped.get(violation.ruleId)!.push(violation);
    }

    return grouped;
  }

  private renderFooter(context: OutputContext): string {
    let footer = chalk.gray('─'.repeat(50)) + '\n\n';
    footer += chalk.gray(
      `Generated by PromptShield on ${context.metadata.scanDate}\n`
    );

    return footer;
  }

  getExtension(): string {
    return '.txt';
  }

  getMimeType(): string {
    return 'text/plain';
  }

  supportsStreaming(): boolean {
    return true;
  }

  async stream(
    results: ScanResult[],
    context: OutputContext,
    writable: NodeJS.WritableStream
  ): Promise<void> {
    const output = this.render(results, context);
    writable.write(output);
  }
}
