/**
 * Markdown output renderer for PromptShield
 * Provides readable, well-structured markdown reports
 */

import { ScanResult, Violation } from '../../types/core/rule';
import { OutputContext } from '../../types/core/outputFormat';
import { OutputRenderer } from './index';
import { Writable } from 'stream';
import {
  sanitizeMarkdown,
  getSeverityEmoji,
} from '../../utils/markdown/markdownUtils';
import {
  formatSeverityBreakdownForMarkdown,
  formatCategoryBreakdownForMarkdown,
  formatOptionsForMarkdown,
  formatFiltersForMarkdown,
} from '../../utils/markdown/markdownUtils';
import { createViolationContext } from '../../utils/markdown/markdownUtils';

export class MarkdownRenderer implements OutputRenderer {
  render(results: ScanResult[], context: OutputContext): string {
    let output = this.renderHeader(context);
    output += this.renderSummary(context);
    output += this.renderResults(results);

    // Add summary at bottom for long outputs (> 10 violations)
    if (context.metadata.totalViolations > 10) {
      output += this.renderBottomSummary(context);
    }

    output += this.renderFooter(context);

    return output;
  }

  private renderHeader(context: OutputContext): string {
    let header = '# PromptShield Scan Report\n\n';

    header += `**Scan Date:** ${context.metadata.scanDate}\n`;
    if (context.metadata.rulepack) {
      header += `**RulePack:** ${context.metadata.rulepack}\n`;
    }
    header += `**Files Scanned:** ${context.metadata.fileCount}\n`;
    header += `**Total Violations:** ${context.metadata.totalViolations}\n\n`;

    header += formatFiltersForMarkdown(context.metadata.filters);

    return header;
  }

  private renderSummary(context: OutputContext): string {
    let summary = '## Summary\n\n';

    summary += formatSeverityBreakdownForMarkdown(
      context.metadata.severityBreakdown
    );
    summary += formatCategoryBreakdownForMarkdown(
      context.metadata.categoryBreakdown
    );

    return summary;
  }

  private renderBottomSummary(context: OutputContext): string {
    let summary = '## 📊 Summary (Repeated for Long Reports)\n\n';

    summary += `**Total Violations:** ${context.metadata.totalViolations}\n`;
    summary += `**Files Scanned:** ${context.metadata.fileCount}\n\n`;

    summary += formatSeverityBreakdownForMarkdown(
      context.metadata.severityBreakdown
    );
    summary += formatCategoryBreakdownForMarkdown(
      context.metadata.categoryBreakdown
    );

    return summary;
  }

  private renderResults(results: ScanResult[]): string {
    if (results.length === 0) {
      return '## Results\n\nNo files were processed.\n\n';
    }

    let resultsSection = '## Results\n\n';

    for (const result of results) {
      // More prominent file headers
      resultsSection += `### 📄 File: ${sanitizeMarkdown(result.file)}\n`;
      resultsSection += `---\n\n`;

      if (result.violations.length === 0) {
        resultsSection += '✅ No violations found.\n\n';
      } else {
        // Group violations by rule ID to reduce repetition
        const groupedViolations = this.groupViolationsByRule(result.violations);

        for (const [ruleId, violations] of groupedViolations) {
          const firstViolation = violations[0];
          const emoji = getSeverityEmoji();

          resultsSection += `#### ${emoji} **[${sanitizeMarkdown(firstViolation.severity.toUpperCase())}]** \`${sanitizeMarkdown(ruleId)}\` (${sanitizeMarkdown(firstViolation.category)})\n`;
          resultsSection += `**Rule:** ${sanitizeMarkdown(firstViolation.message)}\n`;
          resultsSection += `**Occurrences:** ${violations.length}\n\n`;

          // List all matches for this rule
          for (const violation of violations) {
            const context = createViolationContext(violation);
            const lineInfo = violation.lineNumber
              ? ` (${result.file}:${violation.lineNumber})`
              : '';
            resultsSection += `- **Match:** \`${sanitizeMarkdown(violation.match)}\`${context}${lineInfo}\n`;
          }
          resultsSection += '\n';
        }
      }
    }

    return resultsSection;
  }

  private groupViolationsByRule(
    violations: Violation[]
  ): Map<string, Violation[]> {
    const grouped = new Map<string, Violation[]>();

    for (const violation of violations) {
      if (!grouped.has(violation.ruleId)) {
        grouped.set(violation.ruleId, []);
      }
      grouped.get(violation.ruleId)!.push(violation);
    }

    return grouped;
  }

  private renderFooter(context: OutputContext): string {
    let footer = '---\n\n';
    footer += `*Generated by PromptShield on ${context.metadata.scanDate}*\n`;
    footer += formatOptionsForMarkdown(context.metadata.options);

    return footer;
  }

  getExtension(): string {
    return '.md';
  }

  getMimeType(): string {
    return 'text/markdown';
  }

  supportsStreaming(): boolean {
    return true; // Markdown can be streamed
  }

  async stream(
    results: ScanResult[],
    context: OutputContext,
    writable: Writable
  ): Promise<void> {
    // Write header
    if (!writable.write(this.renderHeader(context))) {
      await new Promise((resolve) => writable.once('drain', resolve));
    }
    if (!writable.write(this.renderSummary(context))) {
      await new Promise((resolve) => writable.once('drain', resolve));
    }
    // Write results section header
    if (!writable.write('## Results\n\n')) {
      await new Promise((resolve) => writable.once('drain', resolve));
    }

    for (const result of results) {
      // More prominent file headers
      let fileHeader = `### 📄 File: ${sanitizeMarkdown(result.file)}\n---\n\n`;
      if (!writable.write(fileHeader)) {
        await new Promise((resolve) => writable.once('drain', resolve));
      }

      if (result.violations.length === 0) {
        if (!writable.write('✅ No violations found.\n\n')) {
          await new Promise((resolve) => writable.once('drain', resolve));
        }
      } else {
        // Group violations by rule ID to reduce repetition
        const groupedViolations = this.groupViolationsByRule(result.violations);

        for (const [ruleId, violations] of groupedViolations) {
          const firstViolation = violations[0];
          const emoji = getSeverityEmoji();

          const ruleHeader = `#### ${emoji} **[${sanitizeMarkdown(firstViolation.severity.toUpperCase())}]** \`${sanitizeMarkdown(ruleId)}\` (${sanitizeMarkdown(firstViolation.category)})\n`;
          const ruleInfo = `**Rule:** ${sanitizeMarkdown(firstViolation.message)}\n`;
          const occurrences = `**Occurrences:** ${violations.length}\n\n`;

          if (!writable.write(ruleHeader)) {
            await new Promise((resolve) => writable.once('drain', resolve));
          }
          if (!writable.write(ruleInfo)) {
            await new Promise((resolve) => writable.once('drain', resolve));
          }
          if (!writable.write(occurrences)) {
            await new Promise((resolve) => writable.once('drain', resolve));
          }

          // List all matches for this rule
          for (const violation of violations) {
            const contextStr = createViolationContext(violation);
            const lineInfo = violation.lineNumber
              ? ` (${result.file}:${violation.lineNumber})`
              : '';
            const matchLine = `- **Match:** \`${sanitizeMarkdown(violation.match)}\`${contextStr}${lineInfo}\n`;
            if (!writable.write(matchLine)) {
              await new Promise((resolve) => writable.once('drain', resolve));
            }
          }
          if (!writable.write('\n')) {
            await new Promise((resolve) => writable.once('drain', resolve));
          }
        }
      }
    }

    // Add summary at bottom for long outputs (> 10 violations)
    if (context.metadata.totalViolations > 10) {
      if (!writable.write(this.renderBottomSummary(context))) {
        await new Promise((resolve) => writable.once('drain', resolve));
      }
    }

    // Write footer
    if (!writable.write(this.renderFooter(context))) {
      await new Promise((resolve) => writable.once('drain', resolve));
    }

    // End the stream and wait for it to finish
    writable.end();
    await new Promise((resolve, reject) => {
      writable.on('finish', resolve);
      writable.on('error', reject);
    });
  }

  private formatViolationTable(violations: Violation[]): string {
    if (violations.length === 0) return '';

    const rows: string[] = [];
    for (const violation of violations) {
      const severity = violation.severity || 'unknown';
      const category = violation.category || 'unknown';
      const ruleId = violation.ruleId || 'unknown';
      const message = violation.message || 'No description available';
      const match = violation.match || 'N/A';
      const objectIndex =
        violation.objectIndex !== undefined ? violation.objectIndex : 'N/A';
      const field = violation.field || 'N/A';
      const lineNumber = violation.lineNumber || 'N/A';

      rows.push(
        `| **${severity.toUpperCase()}** | \`${ruleId}\` (${category}) | ${message} | \`${match}\` | ${objectIndex} | ${field} | ${lineNumber} |`
      );
    }

    return rows.join('\n');
  }
}
