/**
 * Table output renderer for PromptShield
 * Provides clean table formatting for terminal display
 */

import { ScanResult } from '../../types/core/rule';
import { OutputContext } from '../../types/core/outputFormat';
import { OutputRenderer } from './index';
import {
  createTableHeader,
  createTableRow,
  formatFiltersForTable,
  createSeparator,
  getSeverityIcon,
} from '../../utils/table/tableUtils';

export class TableRenderer implements OutputRenderer {
  render(results: ScanResult[], context: OutputContext): string {
    let output = this.renderHeader(context);
    output += this.renderSummary(context);
    output += this.renderResults(results);
    output += this.renderFooter(context);

    return output;
  }

  private renderHeader(context: OutputContext): string {
    let header = 'PromptShield Scan Report\n';
    header += createSeparator(50, '=') + '\n';

    header += `Scan Date: ${context.metadata.scanDate}\n`;
    if (context.metadata.rulepack) {
      header += `RulePack: ${context.metadata.rulepack}\n`;
    }
    header += `Files Scanned: ${context.metadata.fileCount}\n`;
    header += `Total Violations: ${context.metadata.totalViolations}\n\n`;

    header += formatFiltersForTable(context.metadata.filters);

    return header;
  }

  private renderSummary(context: OutputContext): string {
    if (context.metadata.totalViolations === 0) {
      return 'No violations found.\n\n';
    }

    let summary = 'Summary:\n';
    summary += '-'.repeat(20) + '\n';

    // Severity breakdown
    if (Object.keys(context.metadata.severityBreakdown).length > 0) {
      summary += 'Severity Breakdown:\n';
      for (const [severity, count] of Object.entries(
        context.metadata.severityBreakdown
      )) {
        const icon = getSeverityIcon(severity);
        summary += `  ${icon} ${severity}: ${count}\n`;
      }
      summary += '\n';
    }

    // Category breakdown
    if (Object.keys(context.metadata.categoryBreakdown).length > 0) {
      summary += 'Category Breakdown:\n';
      for (const [category, count] of Object.entries(
        context.metadata.categoryBreakdown
      )) {
        summary += `  ${category}: ${count}\n`;
      }
      summary += '\n';
    }

    return summary;
  }

  private renderResults(results: ScanResult[]): string {
    if (results.length === 0) {
      return 'No files were processed.\n\n';
    }

    let resultsSection = 'Results:\n';
    resultsSection += createSeparator(20) + '\n';

    for (const result of results) {
      resultsSection += `File: ${result.file}\n`;

      if (result.violations.length === 0) {
        resultsSection += '  No violations found.\n\n';
      } else {
        // Create table header
        resultsSection += createTableHeader();

        for (const violation of result.violations) {
          resultsSection += createTableRow({
            ...violation,
            file: result.file,
          });
        }

        resultsSection += '\n';
      }
    }

    return resultsSection;
  }

  private renderFooter(context: OutputContext): string {
    let footer = createSeparator(50) + '\n';
    footer += `Generated by PromptShield on ${context.metadata.scanDate}\n`;

    if (context.metadata.options) {
      const options = context.metadata.options;
      if (options.maxViolations || options.offset || options.limit) {
        footer += 'Options: ';
        const opts = [];
        if (options.maxViolations) opts.push(`max=${options.maxViolations}`);
        if (options.offset) opts.push(`offset=${options.offset}`);
        if (options.limit) opts.push(`limit=${options.limit}`);
        footer += opts.join(', ') + '\n';
      }
    }

    return footer;
  }

  getExtension(): string {
    return '.txt';
  }

  getMimeType(): string {
    return 'text/plain';
  }

  supportsStreaming(): boolean {
    return true; // Table format can be streamed
  }
}
