/**
 * Init command runner
 * Bootstraps new rulepack YAML files
 */

import { writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { InitOptions, InitTemplate, InitRule } from './types';
import { getTemplate, getAvailableTemplates } from './templates';
import { logger } from '../../../utils/logger';
import { handleCliError } from '../../../utils/errors';

/**
 * Execute the init command
 * @param filename - Name of the YAML file to create
 * @param options - Init command options
 */
export async function executeInitCommand(
  filename: string,
  options: InitOptions
): Promise<void> {
  try {
    // Ensure filename has .yaml extension
    const yamlFilename =
      filename.endsWith('.yaml') || filename.endsWith('.yml')
        ? filename
        : `${filename}.yaml`;

    const filePath = resolve(yamlFilename);

    // Check if file exists
    if (existsSync(filePath) && !options.force) {
      logger.error(
        `File ${yamlFilename} already exists. Use --force to overwrite.`
      );
      process.exit(1);
    }

    // Get template
    const templateName = options.template || 'basic';
    const template = getTemplate(templateName);

    if (!template) {
      logger.error(`Template '${templateName}' not found.`);
      logger.info(`Available templates: ${getAvailableTemplates().join(', ')}`);
      process.exit(1);
    }

    // Override template values with options
    const finalTemplate = {
      ...template,
      description: options.description || template.description,
      category: options.category || template.category,
    };

    // Generate YAML content
    const yamlContent = generateYamlContent(finalTemplate, yamlFilename);

    // Write file
    writeFileSync(filePath, yamlContent, 'utf8');

    if (!options.quiet) {
      logger.info(`✅ Created RulePack: ${yamlFilename}`);
      logger.info(`📦 Template: ${templateName}`);
      logger.info(`📝 Description: ${finalTemplate.description}`);
      logger.info(`📂 Category: ${finalTemplate.category}`);
      logger.info(`🔧 Rules: ${finalTemplate.rules.length}`);

      if (options.verbose) {
        logger.info(`\nGenerated rules:`);
        for (const rule of finalTemplate.rules) {
          logger.info(`  - ${rule.id} (${rule.severity}): ${rule.description}`);
        }
      }

      logger.info(`\nNext steps:`);
      logger.info(`  1. Edit ${yamlFilename} to customize your rules`);
      logger.info(
        `  2. Test your rules: promptshield test "sample text" --rulepack ${yamlFilename}`
      );
      logger.info(
        `  3. Scan files: promptshield scan data.json --rulepack ${yamlFilename}`
      );
    }
  } catch (error) {
    handleCliError(error, 'init');
  }
}

/**
 * Generate YAML content from template
 */
function generateYamlContent(template: InitTemplate, filename: string): string {
  const now = new Date().toISOString().split('T')[0];

  return `# ${template.name}
# Generated by PromptShield init command
# File: ${filename}
# Created: ${now}

version: '1.0.0'
last_updated: '${now}'
name: ${template.name}
description: ${template.description}
category: ${template.category}

rules:
${template.rules
  .map(
    (rule: InitRule) => `  - id: ${rule.id}
    description: ${rule.description}
    ${
      rule.match_keywords
        ? `match_keywords:
      ${rule.match_keywords.map((keyword: string) => `- '${keyword}'`).join('\n      ')}`
        : ''
    }
    ${
      rule.match_regex
        ? `match_regex:
      ${rule.match_regex.map((regex: string) => `- '${regex}'`).join('\n      ')}`
        : ''
    }
    severity: ${rule.severity}
    category: ${rule.category}
    enabled: ${rule.enabled}
`
  )
  .join('\n')}`;
}

/**
 * List available templates
 */
export function listInitTemplates(): void {
  const templates = getAvailableTemplates();

  logger.info('📋 Available Init Templates:');
  logger.info('');

  for (const templateName of templates) {
    const template = getTemplate(templateName);
    if (template) {
      logger.info(`  ${templateName}`);
      logger.info(`    Description: ${template.description}`);
      logger.info(`    Category: ${template.category}`);
      logger.info(`    Rules: ${template.rules.length}`);
      logger.info('');
    }
  }

  logger.info('Usage: promptshield init <filename> --template <template-name>');
}
